#!/bin/bash
echo "🔍 Checking Docker status..."
echo ""
echo "1. OrbStack process:"
ps aux | grep -i orbstack | grep -v grep || echo "   ❌ OrbStack not running"
echo ""
echo "2. Docker socket:"
ls -la ~/.orbstack/run/docker.sock 2>&1 || echo "   ❌ Socket not found"
echo ""
echo "3. Docker connection test:"
docker ps 2>&1 | head -3 || echo "   ❌ Cannot connect"
echo ""
echo "4. Docker system info:"
docker system df 2>&1 | head -5 || echo "   ❌ Cannot get info"
echo ""
echo "5. Recent OrbStack logs:"
tail -10 ~/.orbstack/log/vmgr.log 2>/dev/null | tail -5 || echo "   ❌ No logs"
